### PR TITLE
Make flag completion opt in

### LINKED ISSUE #19: "completion" may cause user command run unexpectly
The current implementation of `completion` runs command function to parse flags, and exits in the `Parse` function. However, a user command may not call the `Parse` function, then the function will fully execute. This lead to unexpected behavior.

Possible solutions are:

1. let the library user take responsibility to always call `Parse` in command funciton, we document the behavior of `completion` in details.
2. change the design to make sure we don't run user commnd unexpectly, this need to change the basic design of the library, e.g. the API to add commands, flags & arguments parsing, which makes the library complicated.

### PR DESCRIPTION
**Pull request by jxskiss**
This PR makes flag completion opt-in, fix #19.

### CODE REVIEW

File: completion.go [hunk 1]
```diff
@@ -53,7 +55,10 @@ func (p *App) doAutoCompletion(args []string) {
 	if isFlag {
 		tree.suggestFlags(p, userArgs, flagName)
 	} else {
-		tree.suggestCommands(p, userArgs)
+		checkFlag := tree.suggestCommands(p, userArgs)
+		if checkFlag {
+			tree.suggestFlags(p, userArgs, "")
```
Comment (akemrir) [inline completion.go:60]: Good point to move this out, one level up.

File: README.md [hunk 2]
```diff
@@ -281,10 +282,13 @@ If there is slice or map arguments, it will match all following arguments.
 
 ## Shell completion
 
-`mcli` supports generating completion script for `bash`, `zsh`, and `powershell`.
+`mcli` supports auto shell completion for `bash`, `zsh`, `fish`, and `powershell`.
 Use `AddCompletion` to enable the feature, run `program completion [bash|zsh|powershell]`
```
Comment (akemrir) [inline README.md:286]: Maybe this way?

`program help completion [bash|zsh|fish|powershell]`

**Review by akemrir — APPROVED** [review]
Ok, changes look Good. Only one remark about command with usage guide.
